export const ROLES = [
  { slug: "president", name: "President", hierarchy_level: 100 },
  { slug: "vice_president", name: "Vice President", hierarchy_level: 90 },
  { slug: "secretary", name: "Secretary", hierarchy_level: 80 },
  { slug: "treasurer", name: "Treasurer", hierarchy_level: 80 },
  { slug: "technical_head", name: "Technical Head", hierarchy_level: 70 },
  { slug: "social_media_head", name: "Social Media Head", hierarchy_level: 70 },
  { slug: "resource_head", name: "Resource Head", hierarchy_level: 70 },
  { slug: "logistics_head", name: "Logistics Head", hierarchy_level: 70 },
  { slug: "student_lead", name: "Student Lead", hierarchy_level: 60 },
  { slug: "member", name: "Member", hierarchy_level: 10 },
] as const;

export const PERMISSIONS = [
  { slug: "overview.read", name: "View Overview", module: "overview" },
  { slug: "analytics.read", name: "View Analytics", module: "analytics" },
  { slug: "calendar.read", name: "View Calendar", module: "calendar" },
  { slug: "tasks.read", name: "View Tasks", module: "tasks" },
  { slug: "tasks.create", name: "Create Tasks", module: "tasks" },
  { slug: "tasks.assign", name: "Assign Tasks", module: "tasks" },
  { slug: "tasks.approve", name: "Approve Tasks", module: "tasks" },
  { slug: "whiteboard.read", name: "View Whiteboard", module: "whiteboard" },
  { slug: "whiteboard.edit", name: "Edit Whiteboard", module: "whiteboard" },
  { slug: "members.read", name: "View Members", module: "members" },
  { slug: "members.update", name: "Update Members", module: "members" },
  { slug: "roles.read", name: "View Roles", module: "roles" },
  { slug: "roles.assign", name: "Assign Roles", module: "roles" },
  { slug: "roles.manage", name: "Manage Roles", module: "roles" },
  { slug: "permissions.manage", name: "Manage Permissions", module: "permissions" },
  { slug: "departments.read", name: "View Departments", module: "departments" },
  { slug: "departments.manage", name: "Manage Departments", module: "departments" },
  { slug: "projects.read", name: "View Projects", module: "projects" },
  { slug: "projects.manage", name: "Manage Projects", module: "projects" },
  { slug: "events.read", name: "View Events", module: "events" },
  { slug: "events.manage", name: "Manage Events", module: "events" },
  { slug: "events.propose", name: "Propose Events", module: "events" },
  { slug: "meetings.read", name: "View Meetings", module: "meetings" },
  { slug: "meetings.manage", name: "Manage Meetings", module: "meetings" },
  { slug: "attendance.read", name: "View Attendance", module: "attendance" },
  { slug: "attendance.manage", name: "Manage Attendance", module: "attendance" },
  { slug: "inventory.read", name: "View Inventory", module: "inventory" },
  { slug: "inventory.manage", name: "Manage Inventory", module: "inventory" },
  { slug: "finance.read", name: "View Finance", module: "finance" },
  { slug: "finance.manage", name: "Manage Finance", module: "finance" },
  { slug: "sponsors.read", name: "View Sponsors", module: "sponsors" },
  { slug: "sponsors.manage", name: "Manage Sponsors", module: "sponsors" },
  { slug: "certificates.read", name: "View Certificates", module: "certificates" },
  { slug: "certificates.manage", name: "Manage Certificates", module: "certificates" },
  { slug: "announcements.read", name: "View Announcements", module: "announcements" },
  { slug: "announcements.manage", name: "Manage Announcements", module: "announcements" },
  { slug: "reports.read", name: "View Reports", module: "reports" },
  { slug: "reports.export", name: "Export Reports", module: "reports" },
  { slug: "settings.read", name: "View Settings", module: "settings" },
  { slug: "settings.manage", name: "Manage Settings", module: "settings" },
  { slug: "audit.read", name: "View Audit Logs", module: "audit" },
  { slug: "notifications.read", name: "View Notifications", module: "notifications" },
  { slug: "resources.read", name: "View Resources", module: "resources" },
  { slug: "resources.manage", name: "Manage Resources", module: "resources" },
  { slug: "learning.read", name: "View Learning", module: "learning" },
  { slug: "learning.manage", name: "Manage Learning", module: "learning" },
  { slug: "messages.send", name: "Send Messages to Leadership", module: "messages" },
  { slug: "messages.read", name: "Read Leadership Messages", module: "messages" },
  { slug: "profile.read", name: "View Profile", module: "profile" },
  { slug: "profile.update", name: "Update Profile", module: "profile" },
] as const;

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  president: PERMISSIONS.map((p) => p.slug),
  vice_president: PERMISSIONS.filter(
    (p) => !["permissions.manage", "settings.manage"].includes(p.slug),
  ).map((p) => p.slug),
  secretary: [
    "overview.read", "meetings.read", "meetings.manage", "attendance.read", "attendance.manage",
    "announcements.read", "announcements.manage", "reports.read", "reports.export",
    "certificates.read", "certificates.manage", "calendar.read", "notifications.read",
    "profile.read", "profile.update", "members.read",
    "resources.manage", "learning.manage", "messages.read", "events.manage",
  ],
  treasurer: [
    "overview.read", "finance.read", "finance.manage", "sponsors.read", "sponsors.manage",
    "reports.read", "reports.export", "calendar.read", "notifications.read",
    "profile.read", "profile.update",
  ],
  technical_head: [
    "overview.read", "projects.read", "projects.manage", "tasks.read", "tasks.create",
    "tasks.assign", "tasks.approve", "whiteboard.read", "whiteboard.edit",
    "analytics.read", "calendar.read", "notifications.read",
    "profile.read", "profile.update", "members.read",
  ],
  social_media_head: [
    "overview.read", "announcements.read", "announcements.manage", "events.read",
    "analytics.read", "calendar.read", "notifications.read", "profile.read", "profile.update",
  ],
  resource_head: [
    "overview.read", "calendar.read", "notifications.read", "profile.read", "profile.update",
    "members.read", "announcements.read",
  ],
  logistics_head: [
    "overview.read", "inventory.read", "inventory.manage", "events.read", "events.manage",
    "calendar.read", "notifications.read", "profile.read", "profile.update",
  ],
  student_lead: [
    "overview.read", "members.read", "attendance.read", "attendance.manage", "tasks.read",
    "tasks.create", "tasks.assign", "whiteboard.read", "whiteboard.edit",
    "calendar.read", "notifications.read",
    "profile.read", "profile.update",
  ],
  member: [
    "overview.read", "tasks.read", "tasks.create", "tasks.assign", "tasks.approve",
    "whiteboard.read", "whiteboard.edit",
    "events.read", "events.propose", "meetings.read", "attendance.read",
    "certificates.read", "members.read",
    "resources.read", "learning.read", "messages.send",
    "calendar.read", "notifications.read", "profile.read", "profile.update",
  ],
};

export const NAVIGATION = [
  { label: "Overview", href: "/", icon: "layout-dashboard", permission_slug: "overview.read", sort_order: 1 },
  { label: "Analytics", href: "/analytics", icon: "bar-chart-3", permission_slug: "analytics.read", sort_order: 2 },
  { label: "Calendar", href: "/calendar", icon: "calendar", permission_slug: "calendar.read", sort_order: 3 },
  { label: "Tasks", href: "/tasks", icon: "layout-kanban", permission_slug: "tasks.read", sort_order: 4 },
  { label: "Whiteboard", href: "/whiteboard", icon: "pen-tool", permission_slug: "whiteboard.read", sort_order: 5 },
  { label: "Members", href: "/members", icon: "users", permission_slug: "members.read", sort_order: 6 },
  { label: "Projects", href: "/projects", icon: "folder-kanban", permission_slug: "projects.read", sort_order: 7 },
  { label: "Events", href: "/events", icon: "calendar-days", permission_slug: "events.read", sort_order: 8 },
  { label: "Meetings", href: "/meetings", icon: "video", permission_slug: "meetings.read", sort_order: 9 },
  { label: "Learning", href: "/learning", icon: "graduation-cap", permission_slug: "learning.read", sort_order: 10 },
  { label: "Resources", href: "/resources", icon: "book-open", permission_slug: "resources.read", sort_order: 11 },
  { label: "Messages", href: "/messages", icon: "mail", permission_slug: "messages.send", sort_order: 12 },
  { label: "Attendance", href: "/attendance", icon: "user-check", permission_slug: "attendance.read", sort_order: 13 },
  { label: "Finance", href: "/finance", icon: "wallet", permission_slug: "finance.read", sort_order: 14 },
  { label: "Inventory", href: "/inventory", icon: "package", permission_slug: "inventory.read", sort_order: 15 },
  { label: "Announcements", href: "/announcements", icon: "megaphone", permission_slug: "announcements.read", sort_order: 16 },
  { label: "Reports", href: "/reports", icon: "file-text", permission_slug: "reports.read", sort_order: 17 },
  { label: "Profile", href: "/profile", icon: "user", permission_slug: "profile.read", sort_order: 18 },
  { label: "Settings", href: "/settings", icon: "settings", permission_slug: "settings.read", sort_order: 19 },
  { label: "Audit Logs", href: "/audit", icon: "shield", permission_slug: "audit.read", sort_order: 20 },
] as const;

export const DEPARTMENTS = [
  { name: "Technical", slug: "technical" },
  { name: "Social Media", slug: "social-media" },
  { name: "Resources", slug: "resources" },
  { name: "Logistics", slug: "logistics" },
  { name: "Finance", slug: "finance" },
  { name: "General", slug: "general" },
] as const;
